server:
  port: 8763

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  mybatis:
    mapper-locations: mapper/*.xml


